apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-origin-cert-tls
  namespace: ingress-nginx
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cloudflare-origin-cert-tls
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .cert }}"
        tls.key: "{{ .key }}"
    creationPolicy: Owner
  data:
  - secretKey: cert
    remoteRef:
      key: "ingress-ngiinx/cloudflare-origin-cert"
  - secretKey: key
    remoteRef:
      key: "ingress-ngiinx/cloudflare-origin-key"
