apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 24h
  chart:
    spec:
      chart: ingress-nginx
      version: '4.12.4'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 24h
  values:
    controller:
      service:
        loadBalancerIP: "192.168.200.240"
        externalTrafficPolicy: Cluster
        annotations:
          metallb.universe.tf/allow-shared-ip: "true"
      watchIngressWithoutClass: "true"
      kind: DaemonSet
      extraArgs:
        default-ssl-certificate: ingress-nginx/cloudflare-origin-ca-tls
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 200Mi
      config:
        disable-ipv6-dns: "true"
        use-forwarded-headers: "true"
