apiVersion:  networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  namespace: blog
spec:
  rules:
  - host: axe.al
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: 8080
