apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-creds-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: postgres-creds-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: "keycloak-postgres/username"
  - secretKey: password
    remoteRef:
      key: "keycloak-postgres/password"
