apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgBad4PLtQgmSA6BRKyFGDGpr1q+gfZ+kDnS+yV7irxe5QZThOOQV9KwNu/Tjx6kJuWV/vEtG00ysZ0ASMlX1ehBYR3juOF2RfRy1iKdCWHnEZyj3kgMBXwmp7L8oy1EcAExhUv9fttHFmo1lHNZbRJTPSYsSRJvmIOfaEWLOckRLc6GYINQslZszl62kF6/e69j3aSqEJLxLtBsWi45QeUwxtzbky+2Zl3pDg5ggVd4xPSXYJDaEZMbwqk6b6hJ6oNFMOPYGHTTZIW0YrO0IVl67dqdGGi+J93CfhjMqsB0ZgAijwDwn9ATfJWVbx3SieXzrXhFjAj3fR7ElNC26WQwNmcZGqobUgZR6A6cOj/36uBHeL6QdsBP9y2/kq02u+6QjMBxL9ESH11aR6pNZQLCtWQS1RTyU484byE32HjBgzYmdfGv5Mj23p4pjqhgfizRyxLDTS957exhr8aVXreEIaUjKbBaxStmdB0ZiblQFDwJKFnLMJ4oLsP4wH+g7Hg1AuFvYs38uDmB2dP3mmzgCP02ZwqxlZ+0wdaUQGB3EbzB5ztWbKAIPTlTFKb3rTOodixnES9Y0lJohQxbEluU18hieQ7ZZdnlGYNlWz0lCrDky0Rfin1kNd72fDGGou6/Yjna+A7dennpbxSb4s4CS51VO8aJnPHrZ1utBXNUeC5cmiYK3PR7E8Ydz6R7PL/PBFvVKQRmBt7pvdlfAyz3EkZFhXG6AM+38MiYBUBjyr4Dtm9P9LrC69Ggitd0/1szVAm6LvvaA3OGYg1Z/DXIQixKCohRjAfOPjTfr2bi9zqlS3xTiu2Bayf40XJ9OLngI8Rk4+cTE7vdwmOu2m4qkeYvbKQHbSMK7wgxP6phE0rH+4slFknoG8eSccYZatfY/m1+iSacUV/WK60mKu8oH7BQuCzlbfgdY/bIWIk=
  template:
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system
