apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 24h
  chart:
    spec:
      chart: minio
      version: '5.4.0'
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: minio
      interval: 24h
  values:
    mode: standalone
    persistence:
      enabled: true
      size: 50Gi
      storageClass: longhorn
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "1"
    extraEnvVars:
      - name: CI_CD
        value: "true"
    existingSecret: minio-creds-secret
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      hosts:
        - s3.axe.al
      tls:
        - secretName: minio-tls
          hosts:
            - s3.axe.al
    consoleIngress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        external-dns.alpha.kubernetes.io/target: 12406f4c-ecab-4674-a0ea-d4fb72f8f8e4.cfargotunnel.com
        traefik.ingress.kubernetes.io/router.middlewares: traefik-oauth2-proxy@kubernetescrd
      hosts:
        - minio.axe.al
      tls:
        - secretName: minio-console-tls
          hosts:
            - minio.axe.al
    metrics:
      serviceMonitor:
        enabled: true
    users: []
