apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 24h
  chart:
    spec:
      chart: minio
      version: '5.4.0'
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: minio
      interval: 24h
  values:
    mode: standalone
    image:
      tag: RELEASE.2025-07-23T15-54-02Z
    persistence:
      enabled: true
      size: 50Gi
      storageClass: longhorn
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "1"
    extraEnvVars:
      - name: CI_CD
        value: "true"
    existingSecret: minio-creds-secret
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      hosts:
        - s3.axe.al
      tls:
        - secretName: minio-tls
          hosts:
            - s3.axe.al
    consoleIngress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        external-dns.alpha.kubernetes.io/target: 4e66423e-bc9e-46b5-90fa-fe0744fb224c.cfargotunnel.com
        nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://auth.axe.al/oauth2/start?rd=https://$host$escaped_request_uri
      hosts:
        - minio.axe.al
      tls:
        - secretName: minio-console-tls
          hosts:
            - minio.axe.al
    metrics:
      serviceMonitor:
        enabled: true
    users: []
