apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-creds-secret
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: minio-creds-secret
    creationPolicy: Owner
  data:
  - secretKey: rootUser
    remoteRef:
      key: "minio/username"
  - secretKey: rootPassword
    remoteRef:
      key: "minio/password"
