apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production
  namespace: metallb-system
spec:
  addresses:
  - 192.168.200.240-192.168.200.249
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kube-api
  namespace: metallb-system
spec:
  addresses:
  - 192.168.200.200/32
  autoAssign: false
