apiVersion:  networking.k8s.io/v1
kind: Ingress
metadata:
  name: receiver
  namespace: flux-system
spec:
  rules:
  - host: flux.axe.al
    http:
      paths:
      - backend:
          service:
            name: notification-controller
            port: 80
