apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
data:
    token: ENC[AES256_GCM,data:cLqfPalfhBX6I3dovMAOQJbv/Rjo4n2uYHnfJ+EqRZRje19e/jlXGXy0Ynppp2Liji3X30Gq6PM=,iv:hFBxDR7TUTDLuYTeCsy+4um+GcGgS/KdHPhgXDR4mN4=,tag:at6dan9KKtKbH8PW3GUC5Q==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-28T16:39:31Z'
    mac: ENC[AES256_GCM,data:b7vsYO4JB//pw80Un8BTWSP7bXJ4NbpJ82xI3Ay7y+sddxMqk6PgiJ246vF3v03JnRkaSdxtiuI2YtuDiS74xvr31K5Z6jT1aoM0CsYoEfvYHO1oBLDb4CiVTkxzbsPsFzvejis/O0Cv9hhBUFddZQFq+0gYiM+V/M9mHXidlIQ=,iv:87z91bnEPzioqNmSzHlf+cglymMPDUaKMCcriKlN37s=,tag:pkfDutrRJtV5DWn7KNPBkQ==,type:str]
    pgp:
    -   created_at: '2020-12-28T16:39:31Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/nv6Q12Xr1TAQwAzLaYB7G4Y0LHhADi3lnuwvagplZA6ez4IjzaxoiR6tIV
            qYEUTOYcXwRXvsrd4GJLmDeTJ8pm5+mEBwKk6P5FFgJPg5QPPD9Xgoj3pMvMsE8a
            uuRqDV/rEBsUnhomIy9znuqz6PoPWN17yAGvo7LYBIZovAwOqrGgXHNfO3GAMHYn
            4nbJtWxnFDgISUgfq6YtHP3LC1S14iHxn1w33/dt55MwvqE5dGfD4a8IjdUKjD5k
            P3w20csaGzrufc+j6uLPPNVaK8Yf2eZRR/UFRbMw9Cou2p69ql8KlSYgjbOdUb52
            kWNaZOoJAfAd9HThi8grl/1UPTgl2ZqKYisb3lDugjSa/OsegSLajK3m/2FnTHhb
            KV3KBVX41YVABiFWNkOhUiFh9RcA/mH4xvc7bfkghdKBY2ZEzJB2G0toMFpIrfVH
            w9xDNzDrGioeG3kEYkSQg3Ci3fF/wsIVgKwrHOT9I7LpQuDsOyQ/ekL+5fI8V/pZ
            f06cT87ujNF9dhaPTFzZ0lwB2x2d2grU8aSAvHat/S+VafPQSQv6TqAjLKN9Xq+y
            ML0cJwahgUjB4FPoVLC4SXFr9DluEy29wZo/vZLvCbUeWyyB75froeyRVwRBz0eS
            8rtR6KjiAghC3U+2DQ==
            =cTWY
            -----END PGP MESSAGE-----
        fp: 80F070D138EBF2FF4F31AB9C4413F3681DD2FBB0
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
