apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook-token
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: webhook-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: "flux-system/webhook-token"
