apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cloudflare
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: "external-dns/cloudflare-api-token"
  - secretKey: zone-id
    remoteRef:
      key: "external-dns/cloudflare-zone-id"
