apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '3.15.2'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 30m
  values:
    controller:
      service:
        enabled: false
      kind: DaemonSet
      extraArgs:
        default-ssl-certificate: ingress-nginx/cloudflare-origin-ca-tls
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: prometheus
      resources:
        requests:
          cpu: 10m
          memory: 200Mi
    podSecurityPolicy:
      enabled: true