---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.3.0
  values:
    controller:
      service:
        enabled: false
      kind: DaemonSet
      extraArgs:
        default-ssl-certificate: ingress-nginx/cloudflare-origin-ca-tls
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: prometheus
      resources:
        requests:
          cpu: 10m
          memory: 200Mi
    podSecurityPolicy:
      enabled: true