apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hue-exporter
  namespace: hue-exporter
spec:
  encryptedData:
    config.yml: AgCUT5lLEpho8GW+yyBkp2Zs2ZOwfPOfiYFn1iNkU+19fuTI3hrJbZVVOciaswnLsOw7Pc+m2cBVK5yamvL5YLYhFiwbQkafGc81CTwLvE3NaLWrOP4H+3GJ51e9JLODYX9qF/B2/JpcbwpxO7GahAEGlVvAhKyzqNQu1chrNrepcyFjUFm0dD+n/cWazI3sa8ddBEESVlXUR5alIQ4b/Wek3khAzaRipcJDMTq5OOvOj0ZJoHpPV2tTb3FPWakoOf2+S1VZTel6qmt2AdesBkpkCWtN5nCw502qE5M5ae//xmDrswz6zUwkc7VDh1RSmRPDUsP/2sJDexG6KZMXW8FX0UIYXHoi/lyF2QkhUc3IFthSlLLLRIVYOToKBL7hO7HbR2Y8J4Opd48RJh/GUTb+klFji/aKvXSN7WYKuiZHx5KcSuWnCVLBVBuI+HVLh3VkYEiNgwMyLe+/LTj097LAh7bOd3Lfoy24QKB7PO7jHi+xbWKHfbPunZTg6voxFe283rBVVAyf+pAckrvTxQyQZr8Wt5w9izWjBsA+8vxTmZXWcwVHR+gyw6/cTFozH/qayPLG1jtn5z7ouNIpJFoocrPXrFXFz0mynHTji3SMp4+VS1eNpi5rpekXfUswUP3qmhFviidctrOzNK9uEW6kNBeaT6/Kr2B0wZNjz7dx/nZ3HOraaDGeSdEQEGbaxDwj0YFwlECnHqPOg97IutDqnjVSqcFc3aZVSiuiKQjJaQmrjGrIwqbUveTfUXLy4951gmUBkRbJMJtpw6vxNSeqj0qfKcv/h4z3kn0MFrxV7mQ+Es/MKWH9ez1jjDQYv6EwMIm7RqBEmPW5Cw4XRbd8oq4hPh2w1ckqvVAHaFBsAc4HvBQU60fsDqM3YsmjMGu/AyA=
  template:
    metadata:
      creationTimestamp: null
      name: hue-exporter
      namespace: hue-exporter

