apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: goldpinger
  namespace: goldpinger
spec:
  selector:
    matchLabels:
      app: goldpinger
  podMetricsEndpoints:
  - port: http
