---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-local-dns
  namespace: kube-system
  labels:
    name: node-local-dns
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      k8s-app: node-local-dns
