apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 24h
  chart:
    spec:
      chart: external-secrets
      version: '0.19.2'
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
      interval: 24h
  values:
    bitwarden-sdk-server:
      enabled: true
    installCRDs: true
