apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: argo-tunnel
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
