apiVersion: v1
data:
    accesskey: ENC[AES256_GCM,data:4AUES9rAxDUc0gJlR4v6bAo45Hv7Y/02/aTYNQ==,iv:MqbwoYLUgxp2Jt2m/IUFIwgqc0fXzLk/tq2DaU1HL64=,tag:TiBempRUngan25zHNfXWkg==,type:str]
    bucket: ENC[AES256_GCM,data:vwkaLc9Lk/mMa314eOEdbfAMwFE=,iv:OSJ4vIgqa+jWfy2p1x4nd4sVCeb7vAoAbIwGp85eES8=,tag:MPB4pgbwyucHTV+eG/qxhw==,type:str]
    region: ENC[AES256_GCM,data:Dr4HtXobP+Y=,iv:AcRYeCl6Xa/gOKByWJA+Ocaq2o5aN/TBj0ykVDb9qq0=,tag:2/M3D+ukn8GUBDZ2/t+aWw==,type:str]
    regionendpoint: ENC[AES256_GCM,data:VjzIhwMLe/W5OXmIaFBIcmHsZH2GsmmrbZ8x7ibXAl7dnBL2,iv:tjlshO9GM2ylf1G+ZlOOR/cCrhILbnhyEeGPnl8wnLM=,tag:YzZhzdiYAPuHYc+Iiyo3/A==,type:str]
    secretkey: ENC[AES256_GCM,data:FXoEXPy22x0cb0tikxGZv8bmGs+L7E3/Uk8NUSHGyiB3jIJyV+2IQpD+y823bd03,iv:KVL9QZhyAUgpck/nkazQa/xuXfuyWoSLNvaZ8m6vWvY=,tag:AO+QVOag3Am4J2Kc0VwXWA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: s3-credentials
    namespace: registry
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-12T14:17:48Z'
    mac: ENC[AES256_GCM,data:R1kdKpaIowkL2y/X6mvZ309zT+azCPkmvz4MZeKrSwK/pVYoTdkdcBzR1F1mzTx4RG6RRCXdOV/J4h8O8MmXeQzYP8rh274soZpR3noNyxu/XDpYhzwlRLD8IOUfBFAi8bWrOaYkuN8BvxsTEB7kairbdzYfWNqyuu90drPz9I8=,iv:tLRrpjTdW1pzHoJhUruywUvf23DY20sGjMH6CdaZzzQ=,tag:FthtZA+KWbDfbTFlU9potQ==,type:str]
    pgp:
    -   created_at: '2021-04-12T14:17:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/nv6Q12Xr1TAQwAw2ErM8Zl3CfrBGT4EaPfPpJof2KDb0no+MxWumxpfXvX
            zJkQAK+yb4TsQjBq33oXY8Opvj2nvhpVIH27tf61S/RCDty1uNguxfOYZa520cd3
            D+xsdWbqi0GVz05MQyg5owUz3SQ1Md5cPRoEX6ImzK/SwVLUZwq3CH9QcA7KtK1z
            0EL/Ug/AGKIlIGUy6tTU+jzOhqwV0msp1NqBskwWCPzXV8GFxbv3kqjOTLfZVStg
            tYIwX1R/wN6+tIDnBuLOg+accUpvk8MvqT7clyRxkeaAqnPAUd0LjWArg52b1QUx
            NXEeRGawIZHsGtGe0ShDjIrRD6QCOpBTP+A7W90kLLHstqhgWc3YPhjb17ISYfyk
            12qseR5z0cIpdp/egtM4kxAv++aCIaqqCqG4V47lNG6kX8a7O9jQn7Q6D6lx89nl
            R1VqofKshHUvJYF5obAmUD9Pp4mlnfnu46ZqajBbzqF3kgGB6Y/N1dOZfVIqVBqj
            DD7UPCnXTX7dTtiY0ffH0l4BWaEtkf3jDqT2ySGqAh7Ae3CD5X+EyoyRIpwX0/v0
            GLYSzxhkANCm/pgnUnLHiq8+0wXldlfgJQRcAEIGkfhbODmzn4DkVYF/bvym6p/u
            y9hgiOxI2etRDIVPXpB8
            =hyEx
            -----END PGP MESSAGE-----
        fp: 80F070D138EBF2FF4F31AB9C4413F3681DD2FBB0
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
