apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 15m
  path: "./clusters/home.axe.al/infrastructure/prometheus/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: prometheus
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: loki
      namespace: prometheus
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: promtail
      namespace: prometheus
  timeout: 5m
  dependsOn:
    - name: longhorn
    - name: ingress-nginx
