apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lb-announcement-policy
spec:
  interfaces:
  - eth0
  loadBalancerIPs: true
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: kube-vip
spec:
  blocks:
  - cidr: "192.168.200.200/32"
  serviceSelector:
    matchLabels:
      app: kubernetes-vip
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-nginx
spec:
  blocks:
  - cidr: "192.168.200.240/32"
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
