---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: vpa-ca-crt
spec:
  secretName: vpa-ca-tls
  commonName: "vpa_webhook_ca"
  isCA: true
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: vpa-ca-issuer
  namespace: kube-system
spec:
  ca:
    secretName: vpa-ca-tls

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: vpa-webhook-crt
  namespace: kube-system
spec:
  secretName: vpa-webhook-tls
  isCA: false
  dnsNames:
  - vpa-webhook.kube-system.svc
  usages:
  - server auth
  - client auth
  issuerRef:
    name: vpa-ca-issuer
    kind: Issuer