#https://github.com/k3s-io/k3s/issues/2262
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k3s-etcd-pushprox
  namespace: monitoring
spec:
  interval: 24h
  chart:
    spec:
      chart: ./charts/rancher-pushprox/103.0.1
      sourceRef:
        kind: GitRepository
        name: rancher-charts
        namespace: monitoring
      interval: 24h
  values:
    global:
      cattle:
        clusterId: axe.al
        clusterName: axe.al
    component: k3s-etcd
    metricsPort: 2379
    clients:
      useLocalhost: true
      https:
        enabled: true
        certDir: /var/lib/rancher/k3s/server/tls/etcd
        certFile: server-client.crt
        keyFile: server-client.key
        caCertFile: server-ca.crt
      nodeSelctor:
        node-role.kubernetes.io/etcd: "true"
      tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"
