#https://github.com/k3s-io/k3s/issues/2262
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k3s-server-pushprox
  namespace: prometheus
spec:
  interval: 24h
  chart:
    spec:
      chart: rancher-pushprox
      version: '0.1.2'
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: prometheus
      interval: 24h
  values:
    component: k3s-server
    metricsPort: 10251
    clients:
      useLocalhost: true
      nodeSelctor:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"
