apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '12.8.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
      interval: 30m
  values:
    kube-state-metrics:
      image:
        repository: k8s.gcr.io/kube-state-metrics-arm64
        tag: v1.9.5
    alertmanager:
      enabled: false
    grafana:
      additionalDataSources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        editable: false
        basicAuth: false
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: cluster-issuer
        hosts:
        - grafana.home.axe.al
        tls:
        - secretName: grafana-ingress-crt
          hosts:
          - grafana.home.axe.al
      sidecar:
        dashboards:
          searchNamespace: ALL
    prometheus:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: cluster-issuer
        hosts:
        - prometheus.home.axe.al
        tls:
        - secretName: prometheus-ingress-crt
          hosts:
          - prometheus.home.axe.al
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false    