apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: '2.2.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: prometheus
      interval: 30m
  values:
    config:
      chunk_store_config:
        max_look_back_period: 672h
      table_manager:
        retention_deletes_enabled: true
        retention_period: 672h
    serviceMonitor:
      enabled: true
