apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCno1iL+/19C1cY+25ku88LfKdxI+Ioonn8t/aNY8awH9+5/mHQNLqTgj6hV5EmaDTytVl9pjH17SF4eb0SqihF07ho62tXS6BCiYPotpQWLx53+4x5yEmXaRZNU7UFcPQTQEhZsHoBpG8EFDQqeLq38uVn+42PpVj/WSwXadsdRvktNaJQzwYtYQDNqAVkfbM9W9PkXW1M1UZs8oBxSl24tphd6wu55mROnFqnakcaTXE8gDIjqIHmCNLR+HAcTcOuaJ1d5YQYbQnnK7FwmVUZH1xxODFaFGR0eI4GM1XYzkM50ASE27HQnFnmSC3CmHbHNoTdrE/GkP2fDtYRRz5SRKoNoULId1Dt5MRvScBAHxzyuArPDl4iqgyS3bY+f2J6kONwSkimyH7Yoy3W3Tir7LAwtmglOBkI2QGaF04M9KoaVMdyh13Ayd+aKqUH20qQdXMWQYCUviEEFE6aWshBYX+N/k1oViQPSI7Dhjs/Bmf/C+rcBssmg00pImjDmfqefK5BLDOcxjCYh/AhGnzbM5Hf3WQm8Zpfyfi+vTY1d7n1QcIg5MK8po2Qoejm5Qrt0wh1PCV1hWZ3jKSr10PU8kYbexhw9FnSJqGu5cSPLjsMU/ZIyd+2RT55N/u39kHwLDVcfmxZiaYm7j1L9PQ235yQCg/IDp1c1kX6aE4SEs7n2VrAt5jt3HRKemhe+wTkd5iB1MC6QOzgcnGMfHfOQcYdkvVl+1OKsulzo2oWqFv4/rBIz2YK
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system

