apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 24h
  chart:
    spec:
      chart: cert-manager
      version: '1.1.0'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 24h
  install:
    skipCRDs: true
  values:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
