apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 24h
  chart:
    spec:
      chart: cert-manager
      version: '1.18.2'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 24h
  values:
    crds:
      enabled: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  interval: 24h
  chart:
    spec:
      chart: trust-manager
      version: '0.19.0'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 24h
  dependsOn:
    - name: cert-manager
