apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 24h
  url: https://github.com/longhorn/longhorn
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/chart/
