apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 24h
  chart:
    spec:
      chart: longhorn
      version: '1.6.1'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 24h
  values:
    ingress:
      enabled: true
      host: longhorn.axe.al
      tls: true
      tlsSecret: longhorn-ingress-cert
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer
        nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://auth.axe.al/oauth2/start?rd=https://$host$escaped_request_uri
