apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-smb-secret
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: longhorn-smb-secret
    creationPolicy: Owner
  data:
  - secretKey: CIFS_USERNAME
    remoteRef:
      key: "longhorn-backup/username"
  - secretKey: CIFS_PASSWORD
    remoteRef:
      key: "longhorn-backup/password"
