apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  interval: 24h
  chart:
    spec:
      chart: promtail
      version: '6.17.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: logging
      interval: 24h
  values:
    config:
      clients:
      - url: http://loki:3100/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          # Add an additional scrape config for syslog
          - job_name: journal
            journal:
              path: /var/log/journal
              max_age: 12h
              labels:
                job: systemd-journal
            relabel_configs:
              - source_labels:
                  - '__journal__systemd_unit'
                target_label: 'unit'
              - source_labels:
                  - '__journal__hostname'
                target_label: 'hostname'
    extraVolumes:
    - name: journal
      hostPath:
        path: /var/log/journal
    extraVolumeMounts:
    - name: journal
      mountPath: /var/log/journal
      readOnly: true
    serviceMonitor:
      enabled: true
