apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  replicas: 1
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:2021.10
        env:
        - name: TZ
          value: "Europe/Berlin"
        - name: WEBPASSWORD
          value: "admin"
        - name: DNS1
          value: 127.0.0.1#5053
        - name: DNS2
          value: "no"
        - name: DNS_BOGUS_PRIV
          value: "false"
        - name: DNS_FQDN_REQUIRED
          value: "true"
        ports:
        - containerPort: 80
          name: web
        - containerPort: 53
          name: dns
      - name: pihole-exporter
        image: ekofr/pihole-exporter:0.0.9
        env:
        - name: PIHOLE_HOSTNAME
          value: "127.0.0.1"
        - name: PIHOLE_PASSWORD
          value: admin
        - name: PORT
          value: "9617"
        ports:
        - containerPort: 9617
          name: metrics
      - name: cloudflared
        image: axeal/cloudflared:2020.11.11
        env:
        - name: TUNNEL_DNS_PORT
          value: "5053"
        args:
        - "proxy-dns"
