apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  replicas: 1
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:2025.08.0
        env:
        - name: TZ
          value: "Europe/Berlin"
        - name: FTLCONF_webserver_api_password
          value: "admin"
        - name: FTLCONF_dns_upstreams
          value: 127.0.0.1#5053
        - name: FTLCONF_dns_bogusPriv
          value: "false"
        - name: FTLCONF_dns_domainNeeded
          value: "true"
        ports:
        - containerPort: 80
          name: web
        - containerPort: 53
          name: dns
      - name: pihole-exporter
        image: ekofr/pihole-exporter:1.2.0
        env:
        - name: PIHOLE_HOSTNAME
          value: "127.0.0.1"
        - name: PIHOLE_PASSWORD
          value: admin
        - name: PORT
          value: "9617"
        ports:
        - containerPort: 9617
          name: metrics
      - name: cloudflared
        image: cloudflare/cloudflared:2025.8.1
        env:
        - name: TUNNEL_DNS_PORT
          value: "5053"
        args:
        - "proxy-dns"
