apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 24h
  releaseName: snapshot-controller
  chart:
    spec:
      chart: rke2-snapshot-controller
      version: '4.0.003'
      sourceRef:
        kind: HelmRepository
        name: rke2-charts
        namespace: kube-system
      interval: 24h
  dependsOn:
    - name: snapshot-controller-crd
