apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:qIU6cnDnyO77xH/+ZFq00B3qlDGtIaZgxwmxNpiZB08EuUDrYS6xbaSdVEI7IAyAL7iMm+2GDGsspy1UvvzRJz5JmJGjKJwh19xmgT1XN2nQwxTqJ1iqlGHBVWwG28pmgBy86zGpkTjzYvnA82fr4eGUHLEmCRHiHF3AYbfHV6I1OLvRUw4b/qWZUmQfjN0xcznDrd1zv0CR+6+MmThnZrcbIsmWZKLqYwfn+rLP/5fy2eCmlmjo/N6dircsW0XUX06zww==,iv:Nng18EXCiIakq6QNsefzkl0nxdrXd+t01+eKQ04hnr4=,tag:Siy1q/af3z/6ddxjMjeHFA==,type:str]
kind: Secret
metadata:
    name: hue-exporter
    namespace: hue-exporter
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-02T19:12:48Z'
    mac: ENC[AES256_GCM,data:/JUL/WofSntIozLLfLhehRaOILcW+6JUuJSpBbF121ujr007IuOsLi4BgIbIZi5yf1sf3kYe9Hd7sVipDFnpEZgVlngxQrrDRqsHFmoOm7D6A80wjHznSHlPode4S/D/+E5N4CiROQP/TmeczlrBTRytvbkxmd2ap0IW0WwPNr4=,iv:0Ufn1HOyphjG0LwT7+s1+AiGwgllsI/fUyiNh0b7c7E=,tag:i3koX0km54D7rfBq44ZLKQ==,type:str]
    pgp:
    -   created_at: '2021-01-02T19:12:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0iwucVVYXgtAQv/eaOrCCiekeZb6997Qu9HIBxAYy4wy2Yixckaw4N/3M1p
            gLyHiI87AXIVFM1RBjcaTk1ekyWgZSEZaKzuy4WqSjD3hS01sZhFSJAX5QLXdsqm
            W45zdDag2S2KGf2+MBapTW5s3f4KdA9rz6A4VaUNaYvDCvBXhbIjJN+HD+LNlKnu
            uFlRG7OQHsN7RJQrTM1KO/1xxRNLbCGpOxNEmKLJDbcGH9z/2cxzcsVCNXgDfQoT
            dk4WU0EnFgMLCFujuR+H2yPidXbSzn6W19govoGdb5L+iBLgKEuW8h96ZsXIWUxT
            2h8oYrLTKIJ2+qwptPKSTssoQF3MmaBmlbjpQbVoXpolHcwLPpSGxwt1woY9NoaZ
            bTl/uNG9lkeKiQaBcM6Myz3YRTYqAav7w7rrrsR1wvywem0C60H1uM7hY5pC/rAO
            zHilIenfhIb1/pYC/2mFRh8Z2QKrei550Og0lf4KFACRnlhUAFCrSJcJdsDSGzqF
            vX8+ENT3CITZVrz8IJgk0l4BXee+2bTYf3r0dXEK9bF54Pk8V67MeYRG3MH3jWxA
            Rph6ht94NsL8wUFbo2b8/LHCLas/vRuZKvmA+X/NEQl3ob8bEXVXnFJd4wC3KTax
            oBBqvhiYVMdvNw1KRrnb
            =PkXQ
            -----END PGP MESSAGE-----
        fp: AE254F5978665BA581E0B74E2A31290A234B45D8
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
