apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pyroscope
  namespace: pyroscope
spec:
  interval: 24h
  chart:
    spec:
      chart: pyroscope
      version: '1.18.1'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: pyroscope
      interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: pyroscope
spec:
  interval: 24h
  chart:
    spec:
      chart: alloy
      version: '1.6.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: pyroscope
      interval: 24h
  values:
    controller:
      hostNetwork: true
    configMap:
      create: false
      name: alloy-config
      key: config.alloy
