apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-issuer-deploy-job
  namespace: cert-manager
spec:
  template:
    spec:
      containers:
      - name: cluster-issuer-deploy-job
        image: k8s.gcr.io/hyperkube-amd64:v1.18.5
        command:
        - kubectl
        - apply
        - -f
        - /etc/config/cluster-issuer.yaml
        volumeMounts:
        - mountPath: /etc/config
          name: cluster-issuer-secret
      volumes:
      - name: cluster-issuer-secret
        secret:
          secretName: cluster-issuer
      restartPolicy: OnFailure
