apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-issuer-deploy-job
  namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager:cluster-issuer-deploy-job
rules:
- apiGroups:
  - 'cert-manager.io'
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
  - update
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager:cluster-issuer-deploy-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager:cluster-issuer-deploy-job
subjects:
- kind: ServiceAccount
  name: cluster-issuer-deploy-job
  namespace: cert-manager

---
apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-issuer-deploy-job
  namespace: cert-manager
spec:
  template:
    spec:
      containers:
      - name: cluster-issuer-deploy-job
        image: k8s.gcr.io/hyperkube-amd64:v1.18.5
        command:
        - kubectl
        - apply
        - -f
        - /etc/config/cluster-issuer.yaml
        volumeMounts:
        - mountPath: /etc/config
          name: cluster-issuer-secret
      volumes:
      - name: cluster-issuer-secret
        secret:
          secretName: cluster-issuer
      restartPolicy: OnFailure
      serviceAccountName: cluster-issuer-deploy-job
