apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 24h
  chart:
    spec:
      chart: garage
      version: '0.9.1'
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: garage
      interval: 24h
  values:
    garage:
      replicationFactor: 1
      s3:
        api:
          region: "home"
    ingress:
      s3:
        api:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
            cert-manager.io/cluster-issuer: letsencrypt-issuer
          hosts:
            - host: s3.axe.al
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - s3.axe.al
              secretName: s3-tls
        web:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
            cert-manager.io/cluster-issuer: letsencrypt-issuer
            external-dns.alpha.kubernetes.io/target: 12406f4c-ecab-4674-a0ea-d4fb72f8f8e4.cfargotunnel.com
            traefik.ingress.kubernetes.io/router.middlewares: traefik-oauth2-proxy@kubernetescrd
          hosts:
            - host: garage.axe.al
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - garage.axe.al
              secretName: garage-tls
    persistence:
      meta:
        storageClass: "longhorn"
        size: "1Gi"
      data:
        storageClass: "longhorn"
        size: "20Gi"
    deployment:
      replicaCount: 1
    image:
      repository: dxflrs/garage
    monitoring:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
