apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homebridge
  name: homebridge
  namespace: homebridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: config
        image: busybox
        volumeMounts:
        - mountPath: /homebridge-config
          name: homebridge-config
        - mountPath: /homebridge
          name: homebridge
        command: ['sh', '-c', 'cp -RLf /homebridge-config/* /homebridge/ && chown -R 911:911 /homebridge']
      containers:
      - image: oznu/homebridge
        imagePullPolicy: Always
        name: homebridge
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /homebridge
          name: homebridge
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      securityContext:
        fsGroup: 911
      volumes:
      - secret:
          items:
          - key: startup.sh
            path: startup.sh
          - key: config.json
            path: config.json
          - key: package.json
            path: package.json
          - key: auth.json
            path: auth.json
          - key: AccessoryInfo.0EA9A71E9C57.json
            path: persist/AccessoryInfo.0EA9A71E9C57.json
          - key: IdentifierCache.0EA9A71E9C57.json
            path: persist/IdentifierCache.0EA9A71E9C57.json
          secretName: homebridge-config
        name: homebridge-config
      - emptyDir: {}
        name: homebridge
