apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: hue-exporter
  name: hue-exporter
  namespace: hue-exporter
spec:
  ports:
  - name: exporter
    port: 9366
    protocol: TCP
    targetPort: 9366
  selector:
    app.kubernetes.io/name: hue-exporter
  type: ClusterIP
