apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-deploy-job
  namespace: external-dns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-dns-deploy-job
  namespace: external-dns
rules:
- apiGroups:
  - 'apps'
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-dns-deploy-job
  namespace: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-dns-deploy-job
subjects:
- kind: ServiceAccount
  name: external-dns-deploy-job

---
apiVersion: batch/v1
kind: Job
metadata:
  name: external-dns-deploy-job
  namespace: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns-deploy-job
        image: rancher/kubectl:v1.18.6
        command:
        - kubectl
        - apply
        - -f
        - /etc/config/external-dns.yaml
        volumeMounts:
        - mountPath: /etc/config
          name: external-dns
      volumes:
      - name: external-dns
        secret:
          secretName: external-dns
      restartPolicy: OnFailure
      serviceAccountName: external-dns-deploy-job
