apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: '2.1.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: prometheus
      interval: 30m
  values:
    extraScrapConfigs:
    - job_name: journal
      journal:
        path: /var/log/journal
        max_age: 12h
        labels:
          job: systemd-journal
      relabel_configs:
      - source_labels:
        - __journal__systemd_unit
        target_label: unit
      - source_labels:
        - __journal__hostname
        target_label: hostname
    extraVolumes:
    - name: journal
      hostPath:
        path: /var/log/journal
    extraVolumeMounts:
    - name: journal
      mountPath: /var/log/journal
      readOnly: true
    loki:
      serviceName: loki
    serviceMonitor:
      enabled: true
