apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 24h
  path: "./clusters/home.axe.al/infrastructure/loki"
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: loki
      namespace: logging
  timeout: 5m
