apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 24h
  path: "./clusters/home.axe.al/infrastructure/metallb/overlays/production"
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: controller
      namespace: metallb-system
    - apiVersion: apps/v1
      kind: DaemonSet
      name: speaker
      namespace: metallb-system
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
