apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-local-dns
  namespace: flux-system
spec:
  interval: 24h
  path: "./clusters/home.axe.al/infrastructure/node-local-dns/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
