apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 24h
  path: "./clusters/home.axe.al/infrastructure/oauth2-proxy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: oauth2-proxy
      namespace: oauth2-proxy
  timeout: 5m
