apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 24h
  path: "./clusters/home.axe.al/projects/pihole/overlays/production"
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: pihole
      namespace: pihole
  dependsOn:
    - name: metallb
