apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  interval: 24h
  path: "./clusters/home.axe.al/infrastructure/snapshot-controller"
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: snapshot-controller-crd
      namespace: kube-system
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: snapshot-controller
      namespace: kube-system
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: snapshot-validation-webhook
      namespace: kube-system
  timeout: 5m
