apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: system-upgrade
  namespace: flux-system
spec:
  interval: 24h
  path: "./clusters/home.axe.al/infrastructure/system-upgrade"
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
  timeout: 5m
