apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: thanos
  namespace: flux-system
spec:
  interval: 24h
  path: "./clusters/home.axe.al/intrastructure/thanos/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: thanos-store
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: thanos-query
      namespace: monitoring
  dependsOn:
    - name: kube-prometheus-stack
